--------------------------------------------------------
--  DDL for Table DATADICT_EXT
--------------------------------------------------------

  CREATE TABLE "DATADICT_EXT" 
   (	"VFILE" VARCHAR2(26 BYTE), 
	"VFIELDNUM" VARCHAR2(3 BYTE), 
	"VFIELDNAME" VARCHAR2(10 BYTE), 
	"VFIELDTYPE" VARCHAR2(1 BYTE), 
	"VFIELDLEN" VARCHAR2(3 BYTE), 
	"VFIELDDEC" VARCHAR2(3 BYTE), 
	"VFIELDDESC" VARCHAR2(50 BYTE), 
	"VSORT" VARCHAR2(5 BYTE), 
	"VRELREPORT" VARCHAR2(10 BYTE), 
	"VREPORT" VARCHAR2(4 BYTE), 
	"VLABELS" VARCHAR2(5 BYTE), 
	"VMERGE" VARCHAR2(5 BYTE), 
	"VNULL" VARCHAR2(26 BYTE), 
	"VPICTURE" VARCHAR2(61 BYTE), 
	"VDEFAULT" VARCHAR2(26 BYTE), 
	"VWHEN" VARCHAR2(26 BYTE), 
	"VVALID" VARCHAR2(26 BYTE), 
	"VMESSAGE" VARCHAR2(26 BYTE), 
	"VERROR" VARCHAR2(26 BYTE), 
	"VRANGELO" VARCHAR2(26 BYTE), 
	"VRANGEHI" VARCHAR2(26 BYTE), 
	"VCOMMENTS" VARCHAR2(128 BYTE), 
	"VCALCEXPR" VARCHAR2(13 BYTE), 
	"VHELP" VARCHAR2(26 BYTE), 
	"VPREVNAME" VARCHAR2(26 BYTE), 
	"VCPNOTRANS" VARCHAR2(5 BYTE), 
	"VSITYPE" VARCHAR2(5 BYTE), 
	"VSICALC" VARCHAR2(5 BYTE)
   ) 
   ORGANIZATION EXTERNAL 
    ( TYPE ORACLE_LOADER
      DEFAULT DIRECTORY "SI_LOGGING"
      ACCESS PARAMETERS
      ( RECORDS DELIMITED BY NEWLINE
    BADFILE DATADICT
    LOGFILE DATADICT
    DISCARDFILE DATADICT
    FIELDS TERMINATED BY "|"
    missing field VALUES are NULL
    (
      VFILE,
      vFIELDNUM,
      vFIELDNAME,
      vFIELDTYPE,
      vFIELDLEN,
      vFIELDDEC,
      vFIELDDESC,
      VSORT,
      vRELREPORT,
      vREPORT,
      vLABELS,
      VMERGE,
      VNULL,
      vPICTURE,
      VDEFAULT,
      VWHEN,
      VVALID,
      vMESSAGE,
      VERROR,
      vRANGELO,
      vRANGEHI,
      vCOMMENTS,
      vCALCEXPR,
      VHELP,
      vPREVNAME,
      vCPNOTRANS,
      vSITYPE,
      vSICALC
    )
      )
      LOCATION
       ( "SI_PROCESSED":'datadict.csv'
       )
    );
