--------------------------------------------------------
--  DDL for Table DRPS_EXT
--------------------------------------------------------

  CREATE TABLE "DRPS_EXT" 
   (	"VTICKER" VARCHAR2(26 BYTE), 
	"VPHONE" VARCHAR2(26 BYTE), 
	"VDRP" VARCHAR2(26 BYTE), 
	"VPARTOPT" VARCHAR2(26 BYTE), 
	"VCASHOPT" VARCHAR2(26 BYTE), 
	"VCAPLUSOPT" VARCHAR2(26 BYTE), 
	"VDIRECT" VARCHAR2(26 BYTE), 
	"VDIRECTMIN" VARCHAR2(26 BYTE), 
	"VCASH" VARCHAR2(26 BYTE), 
	"VCASHFREQ" VARCHAR2(26 BYTE), 
	"VCASHMAX" VARCHAR2(26 BYTE), 
	"VCASHMIN" VARCHAR2(26 BYTE), 
	"VBROKER" VARCHAR2(26 BYTE), 
	"VSERVCHRG" VARCHAR2(26 BYTE), 
	"VDISCOUNT" VARCHAR2(26 BYTE), 
	"VPHONEAGENT" VARCHAR2(26 BYTE), 
	"VINVEST" VARCHAR2(26 BYTE), 
	"VQUALIFY" VARCHAR2(26 BYTE)
   ) 
   ORGANIZATION EXTERNAL 
    ( TYPE ORACLE_LOADER
      DEFAULT DIRECTORY "SI_LOGGING"
      ACCESS PARAMETERS
      ( RECORDS DELIMITED BY NEWLINE
    BADFILE DRPS
    LOGFILE DRPS
    DISCARDFILE DRPS
    FIELDS TERMINATED BY "|"
    missing field VALUES are NULL
    (
      vTICKER,
      vPHONE,
      vDRP,
      vPARTOPT,
      vCASHOPT,
      vCAPLUSOPT,
      vDIRECT,
      vDIRECTMIN,
      vCASH,
      vCASHFREQ,
      vCASHMAX,
      vCASHMIN,
      vBROKER,
      vSERVCHRG,
      vDISCOUNT,
      vPHONEAGENT,
      vINVEST,
      vQUALIFY
    )
      )
      LOCATION
       ( "SI_PROCESSED":'drps.csv'
       )
    );
