--------------------------------------------------------
--  DDL for Table FILEMAST_EXT
--------------------------------------------------------

  CREATE TABLE "FILEMAST_EXT" 
   (	"VDESCRIP" VARCHAR2(128 BYTE), 
	"VFILE" VARCHAR2(26 BYTE), 
	"VDIRECTORY" VARCHAR2(37 BYTE), 
	"VRUNDIR" VARCHAR2(33 BYTE), 
	"VOPENORDER" VARCHAR2(2 BYTE), 
	"VREPORT" VARCHAR2(5 BYTE), 
	"VLABELS" VARCHAR2(5 BYTE), 
	"VSYSTEM" VARCHAR2(5 BYTE), 
	"VCOMMENTS" VARCHAR2(256 BYTE), 
	"VAUTOOPEN" VARCHAR2(5 BYTE), 
	"VNOUPDATE" VARCHAR2(5 BYTE), 
	"VALIAS" VARCHAR2(8 BYTE), 
	"VDEFFILT" VARCHAR2(26 BYTE), 
	"VCODEPAGE" VARCHAR2(5 BYTE), 
	"VSICOM" VARCHAR2(5 BYTE)
   ) 
   ORGANIZATION EXTERNAL 
    ( TYPE ORACLE_LOADER
      DEFAULT DIRECTORY "SI_LOGGING"
      ACCESS PARAMETERS
      ( RECORDS DELIMITED BY NEWLINE
    BADFILE FILEMAST
    LOGFILE FILEMAST
    DISCARDFILE FILEMAST
    FIELDS TERMINATED BY "|"
    missing field VALUES are NULL
    (
      vDESCRIP,
      VFILE,
      VDIRECTORY,
      vRUNDIR,
      vOPENORDER,
      vREPORT,
      vLABELS,
      VSYSTEM,
      vCOMMENTS,
      vAUTOOPEN,
      vNOUPDATE,
      VALIAS,
      vDEFFILT,
      vCODEPAGE,
      vSICOM
    )
      )
      LOCATION
       ( "SI_PROCESSED":'filemast.csv'
       )
    );
