--------------------------------------------------------
--  File created - Wednesday-March-15-2017   
--------------------------------------------------------
@C:\Neal\aaii\source\externalTables\ALSMAST_EXT.sql
@C:\Neal\aaii\source\externalTables\DATADICT_EXT.sql
@C:\Neal\aaii\source\externalTables\DDVIEWS_EXT.sql
@C:\Neal\aaii\source\externalTables\DRPS_EXT.sql
@C:\Neal\aaii\source\externalTables\FILEMAST_EXT.sql
@C:\Neal\aaii\source\externalTables\INDXMAST_EXT.sql
@C:\Neal\aaii\source\externalTables\LISTMAST_EXT.sql
@C:\Neal\aaii\source\externalTables\RELATION_EXT.sql
@C:\Neal\aaii\source\externalTables\SETUP_EXT.sql
@C:\Neal\aaii\source\externalTables\SI_AVG_EXT.sql
@C:\Neal\aaii\source\externalTables\SI_BSA_EXT.sql
@C:\Neal\aaii\source\externalTables\SI_BSQ_EXT.sql
@C:\Neal\aaii\source\externalTables\SI_CFA_EXT.sql
@C:\Neal\aaii\source\externalTables\SI_CFQ_EXT.sql
@C:\Neal\aaii\source\externalTables\SI_CI_EXT.sql
@C:\Neal\aaii\source\externalTables\SI_DATE_EXT.sql
@C:\Neal\aaii\source\externalTables\SI_DOW_EXT.sql
@C:\Neal\aaii\source\externalTables\SI_EE_EXT.sql
@C:\Neal\aaii\source\externalTables\SI_EXCHG_EXT.sql
@C:\Neal\aaii\source\externalTables\SI_GR_EXT.sql
@C:\Neal\aaii\source\externalTables\SI_ISA_EXT.sql
@C:\Neal\aaii\source\externalTables\SI_ISQ_EXT.sql
@C:\Neal\aaii\source\externalTables\SI_MGAV2_EXT.sql
@C:\Neal\aaii\source\externalTables\SI_MGAVG_EXT.sql
@C:\Neal\aaii\source\externalTables\SI_MGDSC_EXT.sql
@C:\Neal\aaii\source\externalTables\SI_MLT_EXT.sql
@C:\Neal\aaii\source\externalTables\SI_PERC_EXT.sql
@C:\Neal\aaii\source\externalTables\SI_PSD_EXT.sql
@C:\Neal\aaii\source\externalTables\SI_PSDA_EXT.sql
@C:\Neal\aaii\source\externalTables\SI_PSDC_EXT.sql
@C:\Neal\aaii\source\externalTables\SI_PSDD_EXT.sql
@C:\Neal\aaii\source\externalTables\SI_PSDH_EXT.sql
@C:\Neal\aaii\source\externalTables\SI_PSDL_EXT.sql
@C:\Neal\aaii\source\externalTables\SI_PSDV_EXT.sql
@C:\Neal\aaii\source\externalTables\SI_PTYP_EXT.sql
@C:\Neal\aaii\source\externalTables\SI_RAT_EXT.sql
@C:\Neal\aaii\source\externalTables\SI_SP_EXT.sql
@C:\Neal\aaii\source\externalTables\SI_STDVIEW_EXT.sql
@C:\Neal\aaii\source\externalTables\SI_UDF_EXT.sql
@C:\Neal\aaii\source\externalTables\SI_UTYP_EXT.sql
@C:\Neal\aaii\source\externalTables\SI_VAL_EXT.sql
