--------------------------------------------------------
--  DDL for Table SI_CI_EXT
--------------------------------------------------------

  CREATE TABLE "SI_CI_EXT" 
   (	"VCOMPANYID" VARCHAR2(26 BYTE), 
	"VCOMPANY" VARCHAR2(32 BYTE), 
	"VTICKER" VARCHAR2(10 BYTE), 
	"VEXCHANGE" VARCHAR2(4 BYTE), 
	"VSTREET" VARCHAR2(100 BYTE), 
	"VCITY" VARCHAR2(35 BYTE), 
	"VSTATE" VARCHAR2(13 BYTE), 
	"VZIP" VARCHAR2(10 BYTE), 
	"VCOUNTRY" VARCHAR2(20 BYTE), 
	"VPHONE" VARCHAR2(14 BYTE), 
	"VWEBADDR" VARCHAR2(60 BYTE), 
	"VBUSINESS" VARCHAR2(2000 BYTE), 
	"VANALYSTFN" VARCHAR2(289 BYTE), 
	"VIND2DIG" VARCHAR2(339 BYTE), 
	"VIND3DIG" VARCHAR2(254 BYTE), 
	"VSIC" VARCHAR2(377 BYTE), 
	"VDRPAVAIL" VARCHAR2(426 BYTE), 
	"VSP" VARCHAR2(279 BYTE), 
	"VDOW" VARCHAR2(275 BYTE), 
	"VADR" VARCHAR2(352 BYTE), 
	"VEMPLOYEES" VARCHAR2(449 BYTE), 
	"VOPTIONABLE" VARCHAR2(218 BYTE), 
	"VREPNO" VARCHAR2(362 BYTE), 
	"VLASTMOD" VARCHAR2(1024 BYTE), 
	"VNULLFLAGS" VARCHAR2(1024 BYTE)
   ) 
   ORGANIZATION EXTERNAL 
    ( TYPE ORACLE_LOADER
      DEFAULT DIRECTORY "SI_LOGGING"
      ACCESS PARAMETERS
      ( RECORDS DELIMITED BY NEWLINE
    BADFILE SI_CI
    LOGFILE SI_CI
    DISCARDFILE SI_CI
    FIELDS TERMINATED BY "|"
    missing field VALUES are NULL
    (
      vCOMPANYID,
      vCOMPANY,
      vTICKER,
      vEXCHANGE,
      vSTREET,
      vCITY,
      vSTATE,
      vZIP,
      vCOUNTRY,
      vPHONE,
      vWEBADDR,
      vBUSINESS CHAR(2000),
      vANALYSTFN,
      vIND2DIG,
      vIND3DIG,
      vSIC,
      vDRPAVAIL,
      vSP,
      vDOW,
      vADR,
      vEMPLOYEES,
      vOPTIONABLE,
      vREPNO,
      vLASTMOD,
      VNULLFLAGS
    )
      )
      LOCATION
       ( "SI_PROCESSED":'si_ci.csv'
       )
    );
